# **Set Methods (continue)...**

## **pop():**
It Removes and returns an arbitrary element from the set.

In [ ]:
new_list = ['app', 'orange', 'mango']
print(new_list.pop())
print(new_list.pop(1))
print(new_list)

mango
orange
['app']

In [ ]:
my_set = {1, 2, 3, 4, 5}
removed_element = my_set.pop()
print("Removed element:", removed_element)
print("Updated set:", my_set)

Removed element: 1
Updated set: {2, 3, 4, 5}

In [ ]:
my_set = {'apple', 'mango', 'banana'}
removed_element = my_set.pop()
print("Removed element:", removed_element)
print("Updated set:", my_set)

Removed element: apple
Updated set: {'mango', 'banana'}

## **clear():**
It Removes all elements from the set.

In [ ]:
my_dict = {"1": 1, "2": 2}
my_dict.clear()
print(my_dict)

{}

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_set.clear()
print("Cleared set:", my_set)

Cleared set: set()

## **update():**
It Adds all elements from another set to the current set.

In [ ]:
set1 = {1, 2, 3}

set1.update({3, 4, 5})
print("Updated set:", set1)

Updated set: {1, 2, 3, 4, 5}

## **intersection_update():**
It Removes all elements from the set that are not in the other set.

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
print(set1.intersection(set2))
print("set1:", set1)
print("set2", set2)

{3, 4, 5}
set1: {1, 2, 3, 4, 5}
set2 {3, 4, 5, 6, 7}

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
set1.intersection_update(set2)
print("updated set1:", set1)
print("set2:", set2)

updated set1: {3, 4, 5}
set2: {3, 4, 5, 6, 7}

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
set2.intersection_update(set1)
print("updated set1:", set1)
print("set2:", set2)

updated set: {1, 2, 3, 4, 5}
set2: {3, 4, 5}

## **difference_update():**
It Removes all elements from the set that are also present in the other set.

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
set1.difference_update(set2)
print("Difference updated set1:", set1)
print("set2:", set2)

Difference updated set1: {1, 2}
set2: {3, 4, 5, 6, 7}

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
set2.difference_update(set1)
print("set1:", set1)
print("Difference updated set2:", set2)

set1: {1, 2, 3, 4, 5}
Difference updated set2: {6, 7}

## **symmetric_difference():**
It Returns a new set containing the elements that are unique to either of the sets.

In [ ]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
symmetric_diff = set1.symmetric_difference(set2)
print("Symmetric Difference:", symmetric_diff)

Symmetric Difference: {1, 2, 5, 6}

In [ ]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
print("Symmetric Difference", set2.symmetric_difference(set1))

print("set1", set1)
print("set2", set2)

Symmetric Difference {1, 2, 5, 6}
set1 {1, 2, 3, 4}
set2 {3, 4, 5, 6}

## **symmetric_difference_update():**
It Updates the set with the elements that are unique to either of the sets.

In [ ]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
set1.symmetric_difference_update(set2)
print("Symmetric Difference updated set1:", set1)
print("set2:", set2)

Symmetric Difference updated set1: {1, 2, 5, 6}
set2: {3, 4, 5, 6}

In [ ]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
set2.symmetric_difference_update(set1)
print("set1:", set1)
print("Symmetric Difference updated set2:", set2)

set1: {1, 2, 3, 4}
Symmetric Difference updated set2: {1, 2, 5, 6}

## **issubset():**
It returns True if all elements of a set are present in another set (including the possibility of being equal), otherwise, it returns False.

In [ ]:
# Example 1: issubset()
set1 = {1, 2, 3, 4}
set2 = {1, 2}

print(set2.issubset(set1))

if set2.issubset(set1):
    print("set2 is a subset of set1.")
else:
    print("set2 is not a subset of set1.")

# Output: set2 is a subset of set1.

True
set2 is a subset of set1.

In [ ]:
set1 = {2,3}
set2 = {3,2}

print(set2.issubset(set1))

True

In [ ]:
set1 = {5,6}
set2 = {2,3}

print(set2.issubset(set1))

False

## **issuperset():**
It returns True if all elements of another set are present in the calling set (including the possibility of being equal), otherwise, it returns False.

In [ ]:

# Example 2: issuperset()
set3 = {1, 2, 3, 4}
set4 = {1, 2}

if set3.issuperset(set4):
    print("set3 is a superset of set4.")
else:
    print("set3 is not a superset of set4.")

# Output: set3 is a superset of set4.

set3 is a superset of set4.

In [ ]:
set3 = {1,2}
set4 = {2,1}

print(set3.issuperset(set4))

True

In [ ]:
set3 = {1,2,3,4}
set4 = {2,1}

print(set4.issuperset(set3))

False

In [ ]:
# issuperset()

# **Set Membership:**
### Discuss how to check if an element is in a set using the in and not in operators.

In [ ]:
my_set = {1, 2, 3, 4, 5}

# Check if an element is present in the set
if 4 in my_set:
    print("is present in the set.")
else:
    print("not present in the set.")

is present in the set.

In [ ]:
# Check if an element is not present in the set
if 4 not in my_set:
    print("is not present in the set.")
else:
    print("is present in the set.")

is present in the set.

In [ ]:
print(4 not in my_set)

False

# **Set comprehensions:**
Set comprehensions are similar to list comprehensions but create sets instead of lists. They provide a concise and efficient way to create sets based on some conditions or expressions. The syntax for set comprehensions is enclosed in curly braces {}.

In [ ]:
# Example 1: Creating a set of squares of numbers from 1 to 5.

squares = {x**2 for x in range(1, 6)}
print(squares)
# Output: {1, 4, 9, 16, 25}

{1, 4, 9, 16, 25}

In [ ]:
# Example 2: Creating a set of even numbers from a list.

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = {x for x in numbers if x % 2 == 0}
print(even_numbers)
# Output: {2, 4, 6, 8, 10}

{2, 4, 6, 8, 10}

# **Difference between issuperset() and issubset() methods:**

### **issuperset() method:**
The issuperset() method checks if a set contains all the elements of another set. In other words, it returns True if the set it is called upon is a superset of the given set (argument), and False otherwise.

In [ ]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4}

# Check if set1 is a superset of set2
result1 = set1.issuperset(set2)

print(result1)  # Output: True

True

In [ ]:
set2.issuperset(set1)

False

### **issubset() method:**
The issubset() method checks if a set is a subset of another set. It returns True if the set it is called upon is a subset of the given set (argument), and False otherwise.

In [ ]:
# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4}

# Check if set2 is a subset of set1
result2 = set2.issubset(set1)

print(result2)  # Output: True

True

In [ ]:
set1.issubset(set2)

False

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4}

print(set1.issuperset(set2))
print(set1.issubset(set2))

True
False

### **Below example demonstrates both methods:**

In [ ]:
# Define two sets
set_a = {1, 2, 3, 4, 5}
set_b = {3, 4}

# Check if set_a is a superset of set_b
result_superset = set_a.issuperset(set_b)

# Check if set_b is a subset of set_a
result_subset = set_b.issubset(set_a)

print(result_superset)  # Output: True
print(result_subset)    # Output: True

### **Set Comprehension with if-else conditions:**

In [ ]:
# Using set comprehension with if-else
squared_numbers = {num**2 if num % 2 == 0 else num for num in range(1, 11)}

print(squared_numbers)
# Output: {None, 4, None, 16, None, 36, None, 64, None, 100}

{64, 1, 3, 4, 5, 36, 7, 100, 9, 16}

In [ ]:
# Example:

# set can't keep duplicate values so removed multiple even and odd values

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = {'even' if x % 2 == 0 else 'odd' for x in numbers}
print(even_numbers)

{'even', 'odd'}

In [ ]:
# Example 3: Creating a set of unique characters from a string.

text = "hello world"
unique_characters = {char for char in text if char.isalpha()}
print(unique_characters)

{'w', 'h', 'd', 'e', 'r', 'o', 'l'}

In [ ]:
text = "hello    world"
unique_characters = {char for char in text}
print(unique_characters)

{' ', 'h', 'w', 'd', 'e', 'r', 'o', 'l'}

In [ ]:
# Compare two sets for equality: set1 = {1, 2, 3} and set2 = {3, 2, 1}. Print the result of the comparison.

set1 = {1, 2, 3}
set2 = {3, 2, 1}

if set1 == set2:
    print("The sets are equal.")
else:
    print("The sets are not equal.")

The sets are equal.

In [ ]:
# Check if an element exists in a set: set1 = {1, 2, 3}. Check if 2 is present in the set and print the result.

set1 = {1, 2, 3}

if 2 in set1:
    print("2 is present in the set.")
else:
    print("2 is not present in the set.")

2 is present in the set.

In [ ]:
# Create a set with elements from 1 to 10. Find the maximum and minimum elements in the set and print them.

# Create a set with elements from 1 to 10 using set comprehension
my_set = {x for x in range(1, 11)}

# Find the maximum and minimum elements in the set
maximum_element = max(my_set)
minimum_element = min(my_set)

# Print the results
print("Maximum element:", maximum_element)
print("Minimum element:", minimum_element)

Maximum element: 10
Minimum element: 1

In [ ]:
# Check if a set is a subset of another set. Set1: {1, 2}, Set2: {1, 2, 3, 4}. Print the result of the check.

# Define the sets
set1 = {1, 2}
set2 = {1, 2, 3, 4}

# Check if set1 is a subset of set2
is_subset = set1.issubset(set2)

# Print the result of the check
print("Is set1 a subset of set2?", is_subset)

Is set1 a subset of set2? True

In [ ]:
# Check if a set is a proper subset of another set. Set1: {1, 2}, Set2: {1, 2, 3, 4}. Print the result of the check.

# Define the sets
set1 = {1, 2}
set2 = {1, 2, 3, 4}

# Check if set1 is a proper subset of set2
is_proper_subset = set1.issubset(set2) and set1 != set2

# Print the result of the check
print("Is set1 a proper subset of set2?", is_proper_subset)

Is set1 a proper subset of set2? True

# **Lambda Functions Examples:**

1. Write a lambda function that takes two arguments x and y and returns their sum.

In [ ]:
sum_func = lambda x, y: x + y
result = sum_func(5, 3)
print(result)  # Output: 8

8

In [ ]:
sum_func = lambda x, y, z: x + y + z
result = sum_func(5, 3, 2)
print(result)

10

2. Sort a list of dictionaries based on a specific key using a lambda function and the sorted() function.

In [ ]:
people = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35}
]
sorted_people = sorted(people, key=lambda x: x['age'])
print(sorted_people)

[{'name': 'Bob', 'age': 25}, {'name': 'Alice', 'age': 30}, {'name': 'Charlie', 'age': 35}]

3. Write a lambda function that takes three arguments (a, b, and c) and returns the product of the three numbers.

In [ ]:
product_func = lambda a, b, c: a * b * c
result = product_func(2, 3, 4)
print(result)  # Output: 24

24

4. Use a lambda function in a list comprehension to generate a list of squared numbers from a given list of integers.

In [ ]:
# Example list
numbers = [1, 2, 3, 4, 5]

# Using a lambda function in list comprehension to square each number
squared_numbers = [(lambda x: x**2) (item) for item in numbers]

# Output: [1, 4, 9, 16, 25]
print(squared_numbers)

[1, 4, 9, 16, 25]

5. Write a lambda function that takes a number as input and returns "Positive" if it's greater than zero, "Negative" if less than zero, and "Zero" if it's zero.

In [ ]:
check_number = lambda x: "Positive" if x > 0 else "Negative" if x < 0 else "Zero"
print(check_number(5))  # Output: "Positive"
print(check_number(-3))  # Output: "Negative"
print(check_number(0))  # Output: "Zero"

Positive
Negative
Zero

# **Patterns Questions:**

1. Write a Python program to generate a square pattern of stars (*) of size n.

In [ ]:
def square_pattern(n):
    for i in range(n):
        print('* ' * n)

square_pattern(4)
# Output:
# * * * * *
# * * * * *
# * * * * *
# * * * * *
# * * * * *

* * * *
* * * *
* * * *
* * * *

2. Write a Python program to generate a right-angled triangle pattern of stars (*) of height n.

In [ ]:
def right_triangle_pattern(n):
    for i in range(1, n+1):
      print('* ' * i)

right_triangle_pattern(5)
# Output:
# *
# * *
# * * *
# * * * *
# * * * * *

*
* *
* * *
* * * *
* * * * *

3. Write a Python program to generate a diamond pattern of stars (*) of size n.

In [ ]:
# [0,1,2,3,4, 5]
# 3, 2, 1, 0, -1

# range(start, stop, step)

def diamond_pattern(n):
    for i in range(n):
        print(' ' * (n - i - 1), end="")
        print('* ' * (i + 1)) #i = 2, n = 5
    for j in range(n - 2 , -1, -1):
        print(' ' * (n - j - 1) + '* ' * (j + 1)) # n = 5, j = 2

diamond_pattern(5)
# Output:
#     *
#    * *
#   * * *
#  * * * *
# * * * * *
#  * * * *
#   * * *
#    * *
#     *

    *
   * *
  * * *
 * * * *
* * * * *
 * * * *
  * * *
   * *
    *

4. Write a Python program to generate a number pyramid pattern of height n.

In [ ]:
def number_pyramid_pattern(n):
    for i in range(1, n + 1):
        print(' ' * (n - i) + ' '.join(str(j) for j in range(1, i + 1))) # '1', '2', '3'

number_pyramid_pattern(5)
# Output:
#     1
#    1 2
#   1 2 3
#  1 2 3 4
# 1 2 3 4 5

    1
   1 2
  1 2 3
 1 2 3 4
1 2 3 4 5

5. Write a Python program to generate an alphabet pattern using the English alphabet letters, 'A' to 'Z'.

In [ ]:
chr(97)

'a'

In [ ]:
def alphabet_pattern(n):
    for i in range(65, n): # i = 66, chr(66), 66-64 = 2
        print(chr(i) * (i - 64))

alphabet_pattern(70)
# Output:
# A
# BB
# CCC
# DDDD
# EEEEE
# ...
# ZZZZZZZZZZZZZZZZZZZZZZZZZZ

A
BB
CCC
DDDD
EEEEE

6. Write a Python program to generate a reverse right-angled triangle pattern of stars (*) of height n.

In [ ]:
def reverse_right_triangle_pattern(n):
    for i in range(n, 0, -1): # i = 5, i = 4,
        print('* ' * i)

reverse_right_triangle_pattern(5)
# Output:
# * * * * *
# * * * *
# * * *
# * *
# *

* * * * *
* * * *
* * *
* *
*

In [ ]:
def reverse_right_triangle_pattern(n):
    for i in range(1, n+1, 1): # i = 5, i = 4,
        print('* ' * i)

reverse_right_triangle_pattern(5)
# Output:
# * * * * *
# * * * *
# * * *
# * *
# *

*
* *
* * *
* * * *
* * * * *

7. Write a Python program to generate a hollow square pattern of stars (*) of size n.

In [ ]:
def hollow_square_pattern(n):
    for i in range(n): # 0, 4
        if i == 0 or i == n - 1:
            print('* ' * n)
        else:
            print('* ' + '  ' * (n - 2) + '*')


hollow_square_pattern(7)
# Output:
# * * * * *
# *       *
# *       *
# *       *
# * * * * *

* * * * * * *
*           *
*           *
*           *
*           *
*           *
* * * * * * *

# **Some packing and unpacking Questions:**

In [ ]:
# Packing multiple values into a single tuple
person = ('John', 30, 'Male')

# Accessing the packed values
name, age, gender = person
print(name)    # Output: John
print(age)     # Output: 30
print(gender)  # Output: Male

John
30
Male

In [ ]:
# Packing multiple values into a list
numbers = [1, 2, 3, 4, 6, 5]

# Accessing the packed values
first, *rest, last = numbers
print(first)  # Output: 1
print(rest)   # Output: [2, 3, 4]
print(last)   # Output: 5

1
[2, 3, 4, 6]
5

In [ ]:
# Unpacking a dictionary into named variables
person_details = {'name': 'Alice', 'age': 25, 'gender': 'Female'}

# Unpacking dictionary keys into individual variables
name, age, gender = person_details.values()

print(name)    # Output: Alice
print(age)     # Output: 25
print(gender)  # Output: Female

Alice
25
Female

In [ ]:
# Unpacking a list of tuples into separate variables
scores = [('Alice', 85), ('Bob', 92), ('Charlie', 78)]

# Unpacking list of tuples into separate variables
for name, score in scores:
    print(f"{name}'s score is {score}")

Alice's score is 85
Bob's score is 92
Charlie's score is 78

# **Dict packing and unpacking with examples:**

Example 1: Dictionary Packing

In [ ]:
# Dictionary packing
name = 'John'
age = 30
occupation = 'Engineer'

person = {'name': name, 'age': age, 'occupation': occupation}

print(person)
# Output: {'name': 'John', 'age': 30, 'occupation': 'Engineer'}

{'name': 'John', 'age': 30, 'occupation': 'Engineer'}

Example 2: Dictionary Unpacking

In [ ]:
# Dictionary unpacking
person = {'name': 'Alice', 'age': 25, 'occupation': 'Teacher'}

name, age, occupation = person['name'], person['age'], person['occupation']

print(name)        # Output: 'Alice'
print(age)         # Output: 25
print(occupation)  # Output: 'Teacher'

Alice
25
Teacher

Example 3: Unpacking Dictionary as Function Arguments

In [ ]:
# Function that takes three arguments: name, age, and occupation
def print_person_details(name, age, occupation):
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Occupation: {occupation}")

# Dictionary packing
person = {'name': 'Bob', 'age': 35, 'occupation': 'Doctor'}

# Dictionary unpacking as function arguments
print_person_details(**person)

# Output:
# Name: Bob
# Age: 35
# Occupation: Doctor

Name: Bob
Age: 35
Occupation: Doctor

Example 4: Unpacking in a Loop

In [ ]:
# List of dictionaries
people = [
    {'name': 'John', 'age': 30},
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 35}
]

# Unpacking dictionaries in a loop
for person in people:
    name, age = person['name'], person['age']
    print(f"Name: {name}, Age: {age}")

# Output:
# Name: John, Age: 30
# Name: Alice, Age: 25
# Name: Bob, Age: 35

Name: John, Age: 30
Name: Alice, Age: 25
Name: Bob, Age: 35

# **List append() method behaviour with shallow copy:**

### When using shallow copy and the append() method, the behavior can differ depending on whether the items being appended are mutable or immutable.



## 1. **Shallow Copy with Immutable Items:**

When the items being appended to a shallow copy are immutable (e.g., numbers, strings, tuples), the behavior is consistent with regular list behavior, and changes to the original list do not affect the shallow copy.

In [ ]:
# Original list
original_list = [1, 2, 3]

# Shallow copy using the slice operator
shallow_copy = original_list[:]

# Modify the original list
original_list.append(4)

print(original_list)  # Output: [1, 2, 3, 4]
print(shallow_copy)   # Output: [1, 2, 3]

[1, 2, 3, 4]
[1, 2, 3]

### 2. **Shallow Copy with Mutable Items:**

When the items being appended to a shallow copy are mutable (e.g., lists, dictionaries), the behavior is different. Changes to the mutable objects within the original list will also be reflected in the shallow copy, as they both reference the same objects.

In [ ]:
# Original list with nested lists
original_list = [[1, 2], [3, 4]]

# Shallow copy using the slice operator
shallow_copy = original_list[:]

# Modify the original list
original_list[0].append(100)

original_list[1].append(500)


print(original_list)  # Output: [[1, 2, 100], [3, 4]]
print(shallow_copy)   # Output: [[1, 2, 100], [3, 4]]

[[1, 2, 100], [3, 4, 500]]
[[1, 2, 100], [3, 4, 500]]

Here in above example, we created a shallow copy of the original list using the slice operator [:]. When we appended an item to the first nested list of the original list, the change was also reflected in the shallow copy because they share the same nested lists.

---
# **Questions to practice:**

1. Write a function that takes a set {1,3,5,6,8,9} as parameter. The function should repeatedly pop elements from the set and sum them until the set becomes empty. Return the total sum.

2. Write a program that creates a set of country names. Then, using the clear() method, remove all the countries from the set and print the empty set.

3. Write a function that takes a set {'ram', 'rohan', 'jony', 'sita'} as paramter1 and a name "ram" as parameter2. The function should discard the name "ram" if it is present in the set using the discard() method and return the updated set.

4. Given a set of numbers, write a program to discard all even numbers from the set using the discard() method. Print the updated set.

5. Given two sets A and B, write a program to remove all elements that are present in both sets using the remove() method. Print the updated sets A and B.

6. Given a set of animals, write a program to update the set by adding new animals from a another list of animals using the update() method. Print the updated set.

7. Write a program that creates two sets of characters (letters and numbers). Then, update the first set to keep only the characters that are present in both sets using the intersection_update() method. Print the updated set.

8. Write a function that takes two sets of words as parameters. The function should update the first set to remove words that are present in the second set using the difference_update() method and return the updated set.

9. Given a set of integers and a list of integers, write a program to update the set by removing the integers present in the list using the difference_update() method. Print the updated set.

10. Write a program that creates two sets of fruits. Then, find the fruits that are unique to each set (i.e., present in either set A or set B, but not in both) using the symmetric_difference() method. Print the resulting set.

11. Given two sets A and B, write a program to find their symmetric difference using the symmetric_difference() method and store the result in a new set C. Print the set C.

12. Write a function that takes two sets of letters as parameters. The function should update the first set with the letters that are unique to each set (i.e., present in either set A or set B, but not in both) using the symmetric_difference_update() method and return the updated set.

13. Given three sets A, B, and C, write a program to find the symmetric difference between sets A and B using the symmetric_difference_update() method and then update set C with this result. Print the updated set C.

14. Write a function that takes two sets as parameters and returns a new set containing elements that are present in both sets using the in operator.

15. Write a program that creates a set of colors. Then, prompt the user to enter a color and check if the input color is in the set using the not in operator. Print "Color Found" if the color is present in the set, otherwise print "Color Not Found."

16. Write a set comprehension to create a set of squares of numbers from 1 to 10, but only include the squares that are greater than 20.

17. Given a list of numbers, create a set of numbers that are divisible by both 3 and 5 using set comprehension with an if condition.

18. Given a list of strings, create a set of strings that have exactly 3 characters using set comprehension with an if condition.

---
# **Questions to practice:**

1. Given a list of tuples containing a name and age, use a lambda function and sorted to sort the list by name in descending order.

  students = [('Alice', 25), ('Bob', 30), ('Charlie', 22), ('David', 28)]


2. Write a lambda function that takes three parameters a, b, and c, and returns the maximum value among them.


3. Write a lambda function that takes a string and returns a new string with all vowels (aeiou) replaced by '#'.

  input_string = "python"

  output = "pyth#n"

4. Write a lambda function that takes two parameters x and y and returns the x to the power of y i.e. (x^y).

5. Write a lambda function that takes one parameter x and returns True if the number is odd otherwise return False.

  x = 5
  
  output = True

6. Write code for the following pattern:

In [ ]:
"""
        *
      * *
    * * *
  * * * *
* * * * *
"""

7. Write code for the following pattern:

In [ ]:
"""
#
# #
# # #
# # # #
# # # # #
"""

8. Write code for the following pattern:

In [ ]:

"""
   *
  * *
 * * *
* * * *
"""

9. Write code for the following pattern:

In [ ]:
"""
    1
   22
  333
 4444
55555
"""

10. Write code for the following pattern:

In [ ]:
"""
AAAAA
BBBB
CCC
DD
E
"""

---
# **Questions to practice:**


1. Write a Python program to swap the values of two variables without using a third variable.

2. Given a list of integers [1, 2, 3, 4], unpack the elements and store them in four separate variables a, b, c, and d.

3. Write a function that takes 4 arguments and packs them into a list. Then, return that list.

4. Write a function that takes three arguments: name, age, and city. Then, call the function using a dictionary to unpack the values.

5. Write a function that takes two arguments and returns their sum and difference as separate values.

6. Create a nested list list1 = [[1, 2], [3, 4]], and then create a shallow copy list2 using the copy() method. Append a new element [5, 6] to list1 and print both lists.

7. Create a list list1 = [1, 2, 3, 4, 5], and then create a shallow copy list2 using the copy() method. Append a new element [7,9] to list2 and print both lists to see if list1 is also affected.

8. Create a list list1 = [1, 2, 3, 4, 5], and then create a shallow copy list2 using the slice notation. Modify an element in list1, and print both lists to see if list2 is also affected.