# **Dict (Data Type):**

### In a dictionary, data is stored in the form of key-value pairs. A key serves as an identifier or a label, while the corresponding value represents the associated data. This relationship between a key and its value is called mapping.

### Key-value is called an item in dictionary.

### The primary purpose of dictionaries is to provide a way to access data quickly and efficiently based on its key. Unlike sequences such as lists or tuples, which use numerical indices to access elements, dictionaries use keys for lookups. This makes dictionaries suitable for situations where you need to retrieve data based on a specific label or identifier rather than a position.

### The key-value pairs in a dictionary are enclosed in curly braces ({}) and separated by commas.

### In key, we can only use immutable data types (string, int, float, bool, tuple, etc) but in Values, we can use all the mutable and immutable data types.

In [ ]:
new_dict = {}
print(type(new_dict))

<class 'dict'>

In [ ]:
ages = {"Alice": 25, "Bob": 30, "Charlie": 35}

print(ages["Bob"])

30

In [ ]:
d = {1:[1,3], (2,3): {"a":1}, 3: "dghfgjh"}

d[(2,3)]

{'a': 1}

In [ ]:
d[3]

'dghfgjh'

In [ ]:
d2 = {[1,2]: (3,4)}
print(d2)

TypeError: ignored

In [ ]:
d2 = {(3,4): [1,2]}
print(d2)

{(3, 4): [1, 2]}

## **When to use Dict:**

Dictionaries are versatile and can be used in various scenarios:

* Building lookup tables or databases: Dictionaries provide a convenient way to store and retrieve data based on keys, making them suitable for implementing lookup tables or small databases.
* Counting occurrences: Dictionaries can be used to count the frequency of elements in a dataset. The elements can be keys, and the corresponding values can be the count of occurrences.
* Storing configuration settings: Dictionaries are commonly used to store configuration settings, where each setting is represented by a key-value pair.
* Mapping relationships: Dictionaries can be used to map relationships between entities. For example, you can use dictionaries to represent a graph, where each node is a key and the connected nodes are stored as values.

# **Creating Dictionaries with different ways:**

1. **Using curly braces {}:**

In [ ]:
# Empty dictionary
empty_dict = {}

# Dictionary with key-value pairs
person = {"name": "John", "age": 30, "city": "New York"}

# Dictionary with mixed data types
mixed_dict = {"name": "Alice", "age": 25, "grades": [85, 90, 95]}

2. **Using the dict() constructor:**

In [ ]:
# Empty dictionary
empty_dict = dict()

# Dictionary with key-value pairs
person = dict(name="Bob", age=35, city="London")
person

{'name': 'Bob', 'age': 35, 'city': 'London'}

3. **Using the zip() function:**

In [ ]:
# Dictionary from two lists
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]
person_dict = dict(zip(ages, names))
person_dict

{25: 'Alice', 30: 'Bob', 35: 'Charlie'}

# **Accessing Dictionary Elements:**

To access a value in a dictionary, you can use square brackets [] and provide the key inside them.

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}

print(person["name"])  # Output: John
print(person["age"])   # Output: 30
print(person["city"])  # Output: New York

John
30
New York

In [ ]:
person["John"]

KeyError: ignored

In [ ]:
person["country"]

KeyError: ignored

Other way to access using get():

In [ ]:
person = {"name": "John", "id": 30, "city": "New York"}

print(person.get("name"))
print(person.get("gender"))

John
None

In [ ]:
print(person.get("age", 25))

print(person.get("gender", "Male"))  # default value

25
Male

In [ ]:
person

{'name': 'John', 'id': 30, 'city': 'New York'}

## **Checking Key Existence in dict:**

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}

print("name" in person)   # Output: True
print("gender" in person) # Output: False
print("age" not in person) # Output: False

True
False
False

In [ ]:
a = 5
b = 6


# if, if-else, if-elif, if-elif-else, if-elif-elif-else, if-elif-elif,

if a < 5:
  print("a is 5")
elif a == 4:
  print(a)
else:
  print("in else")

in else

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}

if "name" in person:
    person["name"] = "Ram"


print(person)

{'name': 'Ram', 'age': 30, 'city': 'New York'}

In [ ]:


if "age" in person:
    print("Gender:#$%%^^^&&&@#$$")
    print(person['city'])
else:
    print("Gender not specified.")

Gender:#$%%^^^&&&@#$$
New York

# **Iterating Over Dictionaries:**

### 1. **Iterating over Keys:**

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}

# Using keys() method
for key in person.keys():
    print(key)

name
age
city

In [ ]:
# Directly iterating over the dictionary
for key in person:
    print(key)

name
age
city

### 2. **Iterating over Values:**

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}

for value in person.values():
    print(value)

John
30
New York

### 3. **Iterating over Items:**

In [ ]:
person = {"name": "", "age": 30, "city": "New York"}

for key, value in person.items():
    print(key, ":", value)

name :
age : 30
city : New York

# **Dictionary Comprehensions:**

Dictionary comprehensions in Python provide a concise way to create dictionaries using a comprehension syntax. They follow a similar syntax to list comprehensions but generate key-value pairs instead of individual elements.

In [ ]:
# {key_expression: value_expression for item in iterable}

In [ ]:
numbers = [1, 2, 3, 4, 5]

squared_dict = {num: num**2 for num in numbers}

print(squared_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [ ]:
numbers = [1, 2, 3, 4, 5]
even_squared_dict = {num: num**2 for num in numbers if num % 2 == 0}

print(even_squared_dict)

{2: 4, 4: 16}

In [ ]:
fruits = ['apple', 'banana', 'cherry']

fruit_lengths = {fruit: len(fruit) for fruit in fruits}

print(fruit_lengths)

{'apple': 5, 'banana': 6, 'cherry': 6}

In [ ]:
# Reversing Key-Value Pairs
numbers = {1: 'one', 2: 'two', 3: 'three'}

reversed_numbers = {value: key for key, value in numbers.items()}

print(reversed_numbers)

{'one': 1, 'two': 2, 'three': 3}

# **Dict methods:**
## **How to add, update, and delete data to Python dict?**

### **Adding Items:**
To add items to a dictionary, we can use the assignment operator (=) to assign a value to a new key.

In [ ]:
my_dict = {'name': 'John', 'age': 30}

my_dict['city'] = 'New York'

my_dict['country'] = 'ABC'

print(my_dict)
# Output: {'name': 'John', 'age': 30, 'city': 'New York'}

{'name': 'John', 'age': 30, 'city': 'New York', 'country': 'ABC'}

### **Updating Items:**
To update the value of an existing key in the dictionary, we can simply reassign a new value to that key.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

my_dict['age'] = 31

my_dict['ag'] = 32

print(my_dict)
# Output: {'name': 'John', 'age': 31, 'city': 'New York'}

{'name': 'John', 'age': 31, 'city': 'New York', 'ag': 32}

In [ ]:
new_dict = {'id': 1, 'id': 2, 'name': 'ram'}

new_dict

{'id': 2, 'name': 'ram'}

### **We can also use the update() method to update multiple key-value pairs at once:**

In [ ]:
my_dict = {'name': 'John', 'age': 30}
new_data = {'age': 31, 'city': 'New York', 'country': 'ABC'}

my_dict.update(new_data)

print(my_dict)
# Output: {'name': 'John', 'age': 31, 'city': 'New York'}

{'name': 'John', 'age': 31, 'city': 'New York', 'country': 'ABC'}

### **Deleting Items:**
To delete an item from a dictionary, we can use the del keyword or the pop() method.

## **Using del:**

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

del my_dict['age']

print(my_dict)
# Output: {'name': 'John', 'city': 'New York'}

SyntaxError: ignored

### **Using pop():**

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

my_dict.pop('age')

print(my_dict)
# Output: {'name': 'John', 'city': 'New York'}

{'name': 'John', 'city': 'New York'}

### **The pop() method can also return the value of the deleted key.**

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

age_value = my_dict.pop('age')

print(age_value)

print(my_dict)
# Output: 30

30
{'name': 'John', 'city': 'New York'}

## **dict.clear():**
It Removes all elements from the dictionary.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
my_dict.clear()
print(my_dict)  # Output: {}

{}

## **dict.copy():**
It Returns a shallow copy of the dictionary.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
new_dict = my_dict.copy()
print(new_dict)  # Output: {'name': 'John', 'age': 30, 'city': 'New York'}

print(id(my_dict), id(new_dict))

{'name': 'John', 'age': 30, 'city': 'New York'}
136619031678336 136619031678976

## **dict.get(key, default):**
It Returns the value for the given key. If the key is not found, it returns the default value.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

print(my_dict.get('name'))  # Output: John
print(my_dict.get('gender', 'F'))
print(my_dict.get('gender'))

John
F
None

## **dict.items():**
It Returns a view object that displays a list of key-value tuples.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

print(my_dict.items())  # Output: dict_items([('name', 'John'), ('age', 30), ('city', 'New York')])

list(my_dict.items())

dict_items([('name', 'John'), ('age', 30), ('city', 'New York')])

[('name', 'John'), ('age', 30), ('city', 'New York')]

In [ ]:
dict(my_dict.items())

{'name': 'John', 'age': 30, 'city': 'New York'}

## **dict.keys():**
It Returns a view object that displays a list of all the keys in the dictionary.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
print(my_dict.keys())  # Output: dict_keys(['name', 'age', 'city'])

list(my_dict.keys())

dict_keys(['name', 'age', 'city'])

['name', 'age', 'city']

## **dict.values():**
It Returns a view object that displays a list of all the values in the dictionary.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
print(my_dict.values())  # Output: dict_values(['John', 30, 'New York'])

list(my_dict.values())

dict_values(['John', 30, 'New York'])

['John', 30, 'New York']

## **dict.pop(key):**
It Removes the element with the specified key and returns its value.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

removed_value = my_dict.pop('age')

print(removed_value)  # Output: 30
print(my_dict)  # Output: {'name': 'John', 'city': 'New York'}

30
{'name': 'John', 'city': 'New York'}

## **dict.popitem():**
It Removes and returns the last key-value pair as a tuple.

In [ ]:
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

removed_item = my_dict.popitem()

print(removed_item)  # Output: ('city', 'New York')
print(my_dict)  # Output: {'name': 'John', 'age': 30}

('city', 'New York')
{'name': 'John', 'age': 30}

## **dict.update(other_dict):**
It Updates the dictionary with the key-value pairs from the specified dictionary.

In [ ]:
my_dict = {'name': 'John', 'age': 30}
other_dict = {'city': 'New York', 'gender': 'Male'}
my_dict.update(other_dict)
print(my_dict)  # Output: {'name': 'John', 'age': 30, 'city': 'New York', 'gender': 'Male'}

{'name': 'John', 'age': 30, 'city': 'New York', 'gender': 'Male'}

## **dict.fromkeys(keys, value):**
It Returns a new dictionary with the specified keys and values.

In [ ]:
keys = ['name', 'age', 'city']
value = 'Unknown'
new_dict = dict.fromkeys(keys, value)
print(new_dict)  # Output: {'name': 'Unknown', 'age': 'Unknown', 'city': 'Unknown'}

{'name': 'Unknown', 'age': 'Unknown', 'city': 'Unknown'}

In [ ]:
keys = ['name', 'age', 'city']
value = ['sita', 28, 'delhi']

dict(zip(keys,value))

{'name': 'sita', 'age': 28, 'city': 'delhi'}

# **Nested Dictionaries:**

Nested dictionaries are dictionaries that contain other dictionaries as their values. This allows us to create complex data structures with multiple levels of key-value pairs.

## **Creating Nested Dictionaries:**
We can create a nested dictionary by assigning a dictionary as a value to a key in another dictionary.

In [ ]:
# Creating a nested dictionary
student_data = {
    'John': {'age': 25, 'major': 'Computer Science'},
    'Alice': {'age': 22, 'major': 'Mathematics'}
}

print(student_data)

{'John': {'age': 25, 'major': 'Computer Science'}, 'Alice': {'age': 22, 'major': 'Mathematics'}}

## **Accessing Nested Elements:**
To access elements in a nested dictionary, we can use multiple keys in square brackets to navigate through the levels of nesting.

In [ ]:
# Accessing nested elements

student_data = {
    'students':[{'age': 25, 'major': 'Computer Science'},{'age': 22, 'major': 'Mathematics'},
                {'age': 28, 'major': 'Electronics'},{'age': 21, 'major': 'Mathematics'},
                {'age': 29, 'major': 'Biology'},{'age': 24, 'major': 'Physics'}]
    }

# print(student_data['students'][2]['age'], student_data['students'][-1]['major'])

for i in student_data['students']:
  print(i['age'], i['major'])

# print(student_data['Alice']['major'])

25 Computer Science
22 Mathematics
28 Electronics
21 Mathematics
29 Biology
24 Physics

## **Adding Elements to Nested Dictionaries:**
We can add elements to a nested dictionary by assigning a value to a specific key at any level of nesting.

In [ ]:
# Adding elements to nested dictionary

student_data = {
    'John': {'age': 25, 'major': 'Computer Science'},
    'Alice': {'age': 22, 'major': 'Mathematics'}}

print("Keys:", student_data.keys())

student_data['John']['gender'] = 'Male'

student_data['gender'] = 'Male'

print("Keys:", student_data.keys())

print(student_data)

Keys: dict_keys(['John', 'Alice'])
Keys: dict_keys(['John', 'Alice', 'gender'])
{'John': {'age': 25, 'major': 'Computer Science', 'gender': 'Male'}, 'Alice': {'age': 22, 'major': 'Mathematics'}, 'gender': 'Male'}

## **Modifying Elements in Nested Dictionaries:**
To modify elements in a nested dictionary, simply assign a new value to the specific key.

In [ ]:
# Modifying elements in nested dictionary
student_data = {
    'John': {'age': 25, 'major': 'Computer Science'},
    'Alice': {'age': 22, 'major': 'Mathematics'}}

student_data['Alice']['age'] = 28
print(student_data['Alice'])

{'age': 28, 'major': 'Mathematics'}

## **Deleting Elements from Nested Dictionaries:**
We can delete elements from a nested dictionary using the del statement with multiple keys.

In [ ]:
# Deleting elements from nested dictionary
student_data = {
    'John': {'age': 25, 'major': 'Computer Science', 'gender': 'Male'},
    'Alice': {'age': 22, 'major': 'Mathematics', 'gender': 'Male', 'id': '', 'city': 'Jaipur'}}

print(student_data)

del student_data['John']['gender']

del student_data['Alice']['major']

print(student_data)

print(student_data['Alice']['age'], student_data['Alice']['city'])

{'John': {'age': 25, 'major': 'Computer Science', 'gender': 'Male'}, 'Alice': {'age': 22, 'major': 'Mathematics', 'gender': 'Male', 'id': '', 'city': 'Jaipur'}}
{'John': {'age': 25, 'major': 'Computer Science'}, 'Alice': {'age': 22, 'gender': 'Male', 'id': '', 'city': 'Jaipur'}}
22 Jaipur

## **Iterating Over Nested Dictionaries:**
We can use nested loops to iterate over the keys and values of nested dictionaries.

In [ ]:
# Iterating over nested dictionary
student_data = {
    'John': {'age': 25, 'major': 'Computer Science'},
    'Alice': {'age': 22, 'major': 'Mathematics'},
    'Rohan': {'age': 28, 'major': 'Physics'},
    'Alisha': {'age': 20, 'major': 'Biology'},
    'Ram': {'age': 30, 'major': 'Electronics'}}

for key, value in student_data.items():
  # print(key, value['age'], value['major'])
  print(f"{key}: Age - {value['age']}, Major - {value['major']}")

John: Age - 25, Major - Computer Science
Alice: Age - 22, Major - Mathematics
Rohan: Age - 28, Major - Physics
Alisha: Age - 20, Major - Biology
Ram: Age - 30, Major - Electronics

In [ ]:
for key in student_data.keys():
  print(key)

John
Alice
Rohan
Alisha
Ram

In [ ]:
for value in student_data.values():
  print(value['age'], value['major'])

25 Computer Science
22 Mathematics
28 Physics
20 Biology
30 Electronics

# **Merging Dictionaries using the update() method and using the ** operator:**

In [ ]:
# Merging Dictionaries using the update() method

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
print(dict1)  # Output: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
# Merging dictionaries using the ** operator

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
merged_dict = {**dict1, **dict2}
print(merged_dict)  # Output: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

# **Dictionary Packing and Unpacking:**

## **Dictionary Packing:**
In Python, dictionary packing refers to creating a dictionary by packing multiple key-value pairs together using the ** operator. This allows us to pass multiple keyword arguments to a function or create a new dictionary from existing variables.

In [ ]:
# Dictionary Packing:

def create_person_info(name, age, city):
    person_info = {'name': name, 'age': age, 'city': city}
    return person_info

# Packing multiple keyword arguments into a dictionary
person_data = create_person_info(age=30, name='Alice', city='New York')
print(person_data)  # Output: {'name': 'Alice', 'age': 30, 'city': 'New York'}

{'name': 'Alice', 'age': 30, 'city': 'New York'}

## **Dictionary Unpacking:**
Dictionary unpacking allows us to extract key-value pairs from a dictionary and use them as keyword arguments in a function call or assign them to new variables.

In [ ]:
# Dictionary Unpacking:

def print_person_info(name, age, city):
    return name, age, city

person_data = {'name': 'Alice', 'age': 30, 'city': 'New York'}

# Unpacking the dictionary and passing as keyword arguments to the function
name_, age_, city_ = print_person_info(**person_data)  # Output: Name: Alice, Age: 30, City: New York

print(name_, age_, city_)

Alice 30 New York

# **Dictionary Sorting:**

In Python, dictionaries are unordered collections of key-value pairs. However, you can sort dictionaries by their keys or values using the sorted() function or the itemgetter() function from the operator module.

## **Sorting by Keys:**
To sort a dictionary by its keys, we can use the sorted() function with the key parameter set to None, as the keys are the default basis for sorting. This will return a list of key-value pairs sorted by keys.

In [ ]:
my_dict = {'banana': 3, 'apple': 1, 'orange': 2, 'abc': 4}

# Sorting the dictionary by keys
sorted_dict_by_keys = sorted(my_dict.items())
print(sorted_dict_by_keys)
# Output: [('apple', 1), ('banana', 3), ('orange', 2)]

[('abc', 4), ('apple', 1), ('banana', 3), ('orange', 2)]

## **Sorting by Values:**
To sort a dictionary by its values, we can pass a lambda function as the key parameter to the sorted() function. The lambda function should take the key-value pair as an argument and return the value. This will return a list of key-value pairs sorted by values.

In [ ]:
my_dict = {'banana': 3, 'apple': 1, 'orange': 2}

# Sorting the dictionary by values
sorted_dict_by_values = sorted(my_dict.items(), key=lambda x: x[0])
print(sorted_dict_by_values)
# Output: [('apple', 1), ('orange', 2), ('banana', 3)]

[('apple', 1), ('banana', 3), ('orange', 2)]

In [ ]:
my_dict = {'banana': 3, 'apple': 1, 'orange': 2}

# Sorting the dictionary by values
sorted_dict_by_values = sorted(my_dict.items(), key=lambda x: x[1])
print(sorted_dict_by_values)
# Output: [('apple', 1), ('orange', 2), ('banana', 3)]

[('apple', 1), ('orange', 2), ('banana', 3)]

## **Sorting using itemgetter():**
We can also use the itemgetter() function from the operator module to sort a dictionary by keys or values. It is faster than using lambda functions for larger dictionaries.

In [ ]:
from operator import itemgetter


my_dict = {'banana': 3, 'apple': 1, 'orange': 2}

# Sorting the dictionary by keys
sorted_dict_by_keys = sorted(my_dict.items(), key=itemgetter(0))
print(sorted_dict_by_keys)
# Output: [('apple', 1), ('banana', 3), ('orange', 2)]

# Sorting the dictionary by values
sorted_dict_by_values = sorted(my_dict.items(), key=itemgetter(1))
print(sorted_dict_by_values)
# Output: [('apple', 1), ('orange', 2), ('banana', 3)]

[('apple', 1), ('banana', 3), ('orange', 2)]
[('apple', 1), ('orange', 2), ('banana', 3)]

# **Some examples of dictionary:**

## **Counting Occurrences:**
Dictionaries are frequently used to count the occurrences of elements in a list or string.

In [ ]:
# Counting occurrences of elements in a list
my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 7, 6, 6]
count_dict = {}

for item in my_list:
  if item in count_dict.keys():
    count_dict[item] += 1
  else: # 1, 2
    count_dict[item] = 1
  # print("count_dict", count_dict)

print(count_dict)  # Output: {1: 1, 2: 2, 3: 3, 4: 4}

{1: 1, 2: 2, 3: 3, 4: 4, 5: 1, 7: 1, 6: 2}

In [ ]:
# counting fruits

fruits = ['Apple', 'Orange', 'Apple', 'Banana']

fruit_dict = {}

for f in fruits:
  if f in fruit_dict:
    fruit_dict[f] += 1
  else:
    fruit_dict[f] = 1
  print(fruit_dict)

# print(fruit_dict)

{'Apple': 1}
{'Apple': 1, 'Orange': 1}
{'Apple': 2, 'Orange': 1}
{'Apple': 2, 'Orange': 1, 'Banana': 1}

## **Grouping Data:**
Dictionaries are useful for grouping data based on specific criteria.

In [ ]:
# Grouping students by their grades

students = [
    {'name': 'Alice', 'Section': 'A', 'class': '10'},
    {'name': 'Bob', 'Section': 'B', 'class': '10'},
    {'name': 'Charlie', 'Section': 'A', 'class': '10'},
    {'name': 'David', 'Section': 'C', 'class': '10'}
]


for student in students:
    section = student.get('Section')
    name = student.get('name')
    print(f"{name} is from section {section} .")

Alice is from section None .
Bob is from section None .
Charlie is from section None .
David is from section None .


## **Some real-world scenarios where a dictionary can be useful:**

## 1. **Scenario: Online Shopping Cart:**

### In an online shopping application, if we want to keep track of the items in the user's shopping cart along with their quantities and prices, we can use a dictionary to store this information efficiently.

### Example:

In [ ]:
# Sample dictionary representing the shopping cart
shopping_cart = {
    'apple': {'quantity': 3, 'price': 1.50},
    'banana': {'quantity': 2, 'price': 0.75},
    'orange': {'quantity': 1, 'price': 2.00},
    'grape': {'quantity': 4, 'price': 0.50}
}

# Function to add items to the shopping cart
def add_item(item_name, quantity, price):
    if item_name in shopping_cart:
        # If the item already exists in the cart, update the quantity
        shopping_cart[item_name]['quantity'] += quantity
    else:
        # If the item is not in the cart, add it with the given quantity and price
        shopping_cart[item_name] = {'quantity': quantity, 'price': price}


# Function to calculate the total cost of the items in the cart
def calculate_total_cost():
    cost = 0
    for item in shopping_cart:
        cost += shopping_cart[item]['quantity'] * shopping_cart[item]['price']
    return cost

# Function to display the contents of the shopping cart
def display_shopping_cart():
    print("Shopping Cart:")
    for item in shopping_cart:
        print(f"{item}: Quantity: {shopping_cart[item]['quantity']}, Price: ${shopping_cart[item]['price']}")


# Add items to the cart
add_item('apple', 2, 1.50)
add_item('banana', 3, 0.75)
add_item('mango', 1, 3.00)

# # Display the shopping cart
display_shopping_cart()

# # Calculate and display the total cost
total_cost = calculate_total_cost()
print(f"Total Cost: {total_cost}")

Shopping Cart:
apple: Quantity: 5, Price: $1.5
banana: Quantity: 5, Price: $0.75
orange: Quantity: 1, Price: $2.0
grape: Quantity: 4, Price: $0.5
mango: Quantity: 1, Price: $3.0
Total Cost: 18.25

## 2. **Scenario: Employee Database:**

### In a company's HR system, we want to keep track of information about employees, such as their name, age, department, and salary. We can use a dictionary to store this information for each employee.

### Example:

In [ ]:
# Sample dictionary representing the employee database
employees = {
    '1001': {'name': 'John Doe', 'age': 30, 'department': 'IT', 'salary': 50000},
    '1002': {'name': 'Jane Smith', 'age': 25, 'department': 'HR', 'salary': 45000},
    '1003': {'name': 'Michael Johnson', 'age': 35, 'department': 'Finance', 'salary': 55000}
}

# Function to add a new employee to the database
def add_employee(emp_id, name, age, department, salary):
    employees[emp_id] = {'name': name, 'age': age, 'department': department, 'salary': salary}
    # print(employees)

# Function to update the salary of an employee
def update_salary(emp_id, new_salary):
    if emp_id in employees:
        employees[emp_id]['salary'] = new_salary
    else:
        print("Employee not found!")
    # print(employees)

# Function to display information of a specific employee
def display_employee_info(emp_id):
    if emp_id in employees:
        print(f"Employee ID: {emp_id}")
        for key, value in employees[emp_id].items():
            print(f"{key.upper()}: {value}")
    else:
        print("Employee not found!")

# Add a new employee
add_employee('1004', 'Sarah Johnson', 28, 'Marketing', 48000)

# Update the salary of an employee
update_salary('1002', 47000)

# # Display information of a specific employee
display_employee_info('1004')

Employee ID: 1004
NAME: Sarah Johnson
AGE: 28
DEPARTMENT: Marketing
SALARY: 48000

## **Building Lookup Tables:**
Dictionaries are often used to build lookup tables for quick access to values based on specific keys.

In [ ]:
# Building a lookup table for country codes
country_codes = {
    'USA': '+1',
    'UK': '+44',
    'India': '+91',
    'Germany': '+49',
}

def get_country_code(country):
    return country_codes.get(country, 'Not found')

print(get_country_code('India'))  # Output: '+91'
print(get_country_code('Japan'))  # Output: 'Not found'

+91
Not found

## **Creating Configurations:**
Dictionaries can be used to store configuration settings for applications. This allows for easy access to different configurations based on the keys.

In [ ]:
# Application configurations using a dictionary
configurations = {
    'debug': True,
    'port': 8080,
    'database': 'mydb',
    'max_connections': 100,
}

print(configurations['port'])  # Output: 8080
print(configurations['debug'])  # Output: True

8080
True

# **Set (Data Type):**

### Sets in Python are unordered collections of unique elements.

### The purpose of sets is to store a collection of distinct items, where each item appears only once.

### Sets are useful when you need to check for the existence of an item quickly, or when you want to perform mathematical set operations like union, intersection, and difference.

### Unlike lists and tuples, sets do not allow duplicate elements, and they are not indexed.

### When we try to create a set with duplicate elements, the duplicates will be automatically removed to maintain uniqueness.

### Sets cannot contain mutable objects like lists or other sets, but they can contain immutable objects like strings, integers, and tuples.

### Order of elements in a set may change whenever the set is modified.

## **Creating Sets:**

Sets can be created using curly braces {} or the set() constructor.

In [ ]:
a = {}
print(type(a))

b = {'apple'}
print(type(b))

c = {"a": 1}
print(type(c))

d = {1,2,3}
print(type(d))

e = set()
print(type(e))

<class 'dict'>
<class 'set'>
<class 'dict'>
<class 'set'>
<class 'set'>

In [ ]:
fruits = {'apple', 'banana', 'orange', 'apple', 'orange'}

print(fruits)

{'orange', 'banana', 'apple'}

In [ ]:
colors = set(['red', 'green', 'blue', 'red', 'yellow', 'green'])

print(colors)

{'yellow', 'blue', 'red', 'green'}

In [ ]:
colors[0]

TypeError: ignored

### **Sets cannot contain mutable objects like lists or other sets, but they can contain immutable objects like strings, integers, and tuples.:**

Example:

In [ ]:
set_1 = {[1,2], {'apple', 'orange'}}

print(set_1)

TypeError: ignored

In [ ]:
set_2 = {1,'abc', (7,8)}
print(set_2)

set_3 = {1,'abc', {3,4}}
print(set_3)

{1, (7, 8), 'abc'}

TypeError: ignored

## **Show how to remove duplicate elements from a list and convert it to a set.**

In [ ]:
# Example of set:

# Sample list with duplicate elements
my_list = [1, 2, 2, 3, 4, 4, 5]

# Convert the list to a set to remove duplicates
my_set = set(my_list)

# Print the resulting set
print(my_set)

{1, 2, 3, 4, 5}

# **Set Conversion:**
* List to set
* set to List
* tuple to set
* set to tuple

In [ ]:
# Example: List to set
list_1 = [2,3,3,4]

set_1 = set(list_1)
print(set_1)

{2, 3, 4}

In [ ]:
# Example: set to List

list_2 = list(set_1)

print(list_2)

[2, 3, 4]

In [ ]:
# Example: tuple to set

tuple_1 = (5,6,5,6)

set_2 = set(tuple_1)

print(set_2)

{5, 6}

In [ ]:
# Example: set to tuple

tuple_2 = tuple(set_2)

print(tuple_2)

(5, 6)

# **Set Operations:**

1. **union()**

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using the union() method
union_set = set1.union(set2)
print(union_set)

# # Using the | operator (OR operator)
union_set = set1 | set2
print(union_set)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}

In [ ]:
set1 = {1, 2}
set2 = {3, 4, 5}

# Using the union() method
union_set = set1.union(set2)
print(union_set)

# # Using the | operator (OR operator)
union_set = set1 | set2
print(union_set)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}

2. **intersection()**

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using the intersection() method
intersection_set = set1.intersection(set2)
print(intersection_set)  # Output: {3}

# Using the & operator (AND operator)
intersection_set = set1 & set2
print(intersection_set)  # Output: {3}

{3}
{3}

In [ ]:
set1 = {1, 2}
set2 = {3, 4, 5}

# Using the intersection() method
intersection_set = set1.intersection(set2)
print(intersection_set)

# Using the & operator
intersection_set = set1 & set2
print(intersection_set)

set()
set()

3. **difference()**

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Using the difference() method
difference_set = set1.difference(set2)
print(difference_set)

difference_set = set2.difference(set1)
print(difference_set)

print("---------")
# Using the - operator (NOT operator)
difference_set = set1 - set2
print(difference_set)

difference_set = set2 - set1
print(difference_set)

{1, 2}
{4, 5}
---------
{1, 2}
{4, 5}

4. **add()**

In [ ]:
# Creating a set
fruits = {"apple", "banana", "orange"}

# Adding a new element to the set
fruits.add("grape")
print(fruits)

{'grape', 'orange', 'banana', 'apple'}

In [ ]:
numbers = {1,2,3}

numbers.add(2)
print(numbers)

{1, 2, 3}

5. **remove()**

In [ ]:
# Removing an element from the set
fruits.remove("banana")
print(fruits)  # Output: {'apple', 'grape', 'orange'}

# Trying to remove a non-existent element will raise a KeyError
fruits.remove("pear")  # KeyError: 'pear'
print(fruits)

{'grape', 'orange', 'apple'}

KeyError: ignored

6. **discard()**

In [ ]:
# Removing an element from the set
fruits.discard("apple")
print(fruits)  # Output: {'grape', 'orange'}

# If the element does not exist, `discard()` will not raise an error
fruits.discard("pear")
print(fruits)  # Output: {'grape', 'orange'}

{'grape', 'orange'}
{'grape', 'orange'}

---
# **Questions to Practice:**

1. How do you create an empty dictionary in Python?

2. Create a dictionary named my_dict with the following key-value pairs: "student" -> "Ram", "id" -> 2, "country" -> "India".

3. Access the value associated with the key "id" in the dictionary my_dict using the square bracket notation. For my_dict, use 2nd question's dict.

4. Create a new_dict and Access the value associated with the keys using the get() method.

5. What happens if you try to access a key that does not exist in a dictionary using the square bracket notation? Write a code example for it.

6. Create a new_dict and check if the key "name" exists in the dictionary my_dict using the in operator.

7. Create a new_dict and check the key "id" does not exist in the dictionary my_dict using the not in operator.

8. Write a code snippet to create a dictionary named student using the dict() constructor with the key-value pairs: "name" -> "Alice", "age" -> 20, "city" -> "London".

9. Create a dictionary named book with the keys "title" and "author" and their respective values "Singh" and "Developer" as input by the user.

10. create two lists and create a dict out of them using zip().

---
# **Questions to Practice:**

1. Given the following dictionary, use a for loop to print all the keys one by one.

In [ ]:
my_dict = {'id': 2005, 'student': 'Ram', 'class': '12'}

# code here

2. Given the following dictionary, use a for loop to calculate the sum of all the values.

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40}

# Hint: use for loop using values(), and define sum_values variable to store all the values one by one.
# code here

3. Print all the keys, values from dict using for loop and items().

In [ ]:
my_dict = {'a': 5, 'b': 10, 'c': 15, 'd': 20}

# code here

4. Write a dictionary comprehension to create a dictionary where the keys are the numbers from 1 to 10, and the values are their squares, but only for even numbers.

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]

# code here

5. Write a dictionary comprehension to create a dictionary where the keys are the numbers from 1 to 10, and the values are the cubes of the numbers, but only for numbers that are divisible by 3.

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]

# code here

6. Given a list of numbers, write a dictionary comprehension to create a dictionary where the keys are the numbers, and the values are either "even" or "odd" depending on whether the number is even or odd.

In [ ]:
numbers = [2,5,7,9,11,15,18,20]

even_odd_dict = {num: "even" if num % 2 == 0 else "odd" for num in numbers}

print(even_odd_dict)

{2: 'even', 5: 'odd', 7: 'odd', 9: 'odd', 11: 'odd', 15: 'odd', 18: 'even', 20: 'even'}

7. Write a program that adds a new item to an existing dictionary.

In [ ]:
d = {'a': 1, 'b': 2}

# add 'c': 3
# code here

8. Given a dictionary containing students' names and their corresponding grades, write a program to update a student's grade.

In [ ]:
students = {'ram': 'A', 'sita': 'B', 'john': 'D'}

# update 'john' grade to 'A'
# code here

9. Write a program that removes a specific item from a dictionary using del keyword.

In [ ]:
d = {'ram': 'A', 'sita': 'B', 'john': 'D'}

# remove 'john' from dictionary
# code here

10. Given a dictionary of student names and their corresponding ages, write a program to remove a student from the dictionary and save the removed age in a new variable and print that.

In [ ]:
students = {'ram': 26, 'sita': 24, 'rohan': 27}

# remove 'rohan' from the dictionary and store removed age in a new variable
# code here

11. Write a program that clears all the items from a dictionary.

In [ ]:
d = {'ram': 26, 'sita': 24, 'rohan': 27}

# code here

12. Given a dictionary of student names and their corresponding ages, write a program to remove a student from the dictionary and save the removed complete item in a new variable and print that.

In [ ]:
students = {'ram': 26, 'sita': 24, 'rohan': 27}

# remove 'ram' from the dictionary and store the removed item in a new variable
# code here

13. Given a dictionary, add and update multiple items to it at a time.

In [ ]:
d = {'ram': 26, 'sita': 24, 'rohan': 27}

# update 'ram':30
# update 'rohan':25
# add 'john':28

# code here

14. Write a program that creates a new dictionary with keys from a given list and initializes all values to a default value of 0 using the fromkeys() method.

In [ ]:
my_list = ['a', 'b', 'c']

# code here

15. Given a dictionary of book titles and their respective authors, create a new dictionary with the same keys and values using the copy() method.

In [ ]:
books = {'python': 'Guido van Rossum', 'pandas': 'Wes McKinney', 'numpy': 'Travis Oliphant'}

# code here

---
# **Questions to practice:**

In [ ]:
student_data = {
    'John Doe': {
        'Math': 90,
        'Science': 85,
        'English': 95
    },
    'Jane Smith': {
        'Math': 88,
        'Science': 92,
        'English': 87
    },
    'Mike Johnson': {
        'Math': 78,
        'Science': 80,
        'English': 92
    }
}

### 1. For the above student_data dictionary, Access the grade of a 'Math' subject for 'Mike Johnson' student from the nested dictionary.

In [ ]:
# code here

### 2. For the above student_data dictionary, Modify the grade of a 'Science' subject with 97 for 'Jane Smith' student in the nested dictionary.

In [ ]:
# code here

### 3. Iterate over the student_data dictionary to print the names of all students along with their subjects and grades.
### Hint: use .items() with for loop to iterate.

In [ ]:
# code here

In [ ]:
library_catalog = {
    'book1': {
        'title': 'Python Crash Course',
        'author': 'Eric Matthes',
        'genre': 'Programming',
        'publication_year': 2015
    },
    'book2': {
        'title': 'To Kill a Mockingbird',
        'author': 'Harper Lee',
        'genre': 'Fiction',
        'publication_year': 1960
    }
}

### 4. Add the below new book details to the above library_catalog dictionary.

'book3' = {
        'title': 'The Hobbit',
        'author': 'J.R.R. Tolkien',
        'genre': 'Fantasy',
        'publication_year': 1937}

In [ ]:
# code here

### 5. Remove 'book2' from the library_catalog dictionary.

In [ ]:
# code here

### 6. Iterate over library_catalog dictionary and show all the titles of books only.

In [ ]:
# code here

### 7. Iterate over library_catalog dictionary and show all the auther and their publication_year.

In [ ]:
# code here

### 8.Create two dictionaries, dict1 and dict2, and merge them into a new dictionary merged_dict using the ** operator. then print the merged_dict.

In [ ]:
# code here

### 9. Create three dictionaries, dict1, dict2, and dict3, and merge them into a single dictionary merged_dict using the ** operator. then print the merged_dict.

In [ ]:
# code here

### 10. Create two dictionaries, dict1 and dict2, and merge dict2 into dict1 using the update() method. Then, print the dict1.

In [ ]:
# code here

### 11. Create a function called create_person that takes four arguments: name, age, city, and email. Inside the function, pack these arguments into a dictionary named person_info and return it.

In [ ]:
# code here

### 12. Create a dictionary called student_info with keys: name, age, major, and university. Then, use dictionary unpacking to assign these values to individual variables: student_name, student_age, student_major, and student_university.

In [ ]:
# code here

### 13. Create two dictionaries dict1 and dict2 with some key-value pairs. Use dictionary unpacking to merge both dictionaries into a new dictionary called merged_dict.
### Hint: use **operator with dict1 and dict2

In [ ]:
# code here

---
# **Questions to practice:**

### 1. Write a Python program to sort a dictionary by its keys in ascending order.

### 2. Write a Python program to sort a dictionary by its values in ascending order.

### 3. Sort a dictionary by its keys in descending order.
* ### Syntax for descending order sorting:
* ### **sorted(dict_name.items(), reverse=True)**

### 4. Sort a dictionary by its values in descending order.

### 5. Sort a dictionary by length of its keys in ascending order.
* ### Hint Lambda function: **lambda x: len(x[0])**

---
# **Questions to practice:**

1. Create an empty set and print it.

2. Create a set containing the integers 1, 2, 3, and 4. Print the set.

3. Create a set from a list of strings ['ram', 'radha', 'rohan'] and add new item 'jony' to it and print the result.

4. Create a set from a tuple (1, 2, 3, 4) first and then convert it to a list and print the result.

5. Convert a list [1, 2, 3, 4, 2, 3] to a set and print the set.

6. Create two sets: set1 = {1, 2, 3, 4} and set2 = {3, 4, 5, 6}. Perform a union operation on both sets and print the result.

7. Create two sets: set1 = {1, 2, 3, 4} and set2 = {6,7}. Perform an intersection operation on both sets and print the result.

8. Create two sets: set1 = {1, 2, 3} and set2 = {3, 4, 5}. Perform a difference operation on both sets (set1 - set2) and (set2 - set1) and print the results.

9. Convert a set {1, 2, 3, 4} to a tuple and print the tuple.

10. Create a set from a string "python" and print the set.

11. Create a set with elements from 10 to 20. Find the length of the set and print it.